### ISSUE TITLE
Cannot run the example file

### ISSUE THREAD

**Issue by atkamal** [ladybug-tools/uwg#139] opened 2020-11-03 11:41 UTC
Hi!! My name is Athar and I wanted to run the UWG to understand how it works. 

I am a beginner/ novice to python. 

I cannot seem to run the example that's mentioned in the page. Would like some guidance on this. 

"Here is a Python example that shows how to create and run an Urban Weather Generator object. The example script is available at resources/uwg_example.py. Run it through your command prompt in the main uwg directory with the following: python -m resources.uwg_example

from uwg import uwg

# Define the .epw, .uwg filenames to create an uwg object.
# uwg will look for the .epw file in the uwg/resources/epw folder,
# and the .uwg file in the uwg/resources/parameters folder.
epw_filename = "SGP_Singapore.486980_IWEC.epw"      # .epw file name
param_filename = "initialize_singapore.uwg"         # .uwg file name

# Initialize the UWG object and run the simulation
uwg_ = uwg(epw_filename, param_filename)
uwg_.run() "

**Comment by jumpyapple** [comment] 2020-11-04 13:47
#138 should have the updated example. The render version can be found [here](https://github.com/jumpyapple/uwg/tree/update-readme-example#example). The two files have to be copied out from tests folder

- `SGP_Singapore.486980_IWEC.epw` is from https://github.com/ladybug-tools/uwg/tree/master/tests/epw
- `initialize_singapore.uwg` is from https://github.com/ladybug-tools/uwg/tree/master/tests/parameters

Put those two files next to your Python file.

**Comment by atkamal** [comment] 2020-11-08 06:47
Thank you for your help.

**Comment by atkamal** [comment] 2020-11-09 12:50
Hello !

I tried running the updated code and am getting the following error. 

 _**File "C:\Users\athar.kamal\uwg\uwg\uwg.py", line 1472, in _read_input
    self._init_param_dict[row[0]] = float(row[1])

IndexError: list index out of range**_

Also, when i run the test, I get the following as failed

_**-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ===========================
FAILED ..\tests\test_cli.py::test_model_validate - AssertionError: Model vali...
FAILED ..\tests\test_cli.py::test_param_validate - AssertionError: Validating...
FAILED ..\tests\test_cli.py::test_uwg_simulate - AssertionError: Usage: simul...
FAILED ..\tests\test_cli.py::test_custom_uwg_simulate - AssertionError: Usage...
FAILED ..\tests\test_cli.py::test_param_simulate - AssertionError: Usage: sim...
============= 5 failed, 62 passed, 1 warning in 105.05s (0:01:45) =============**_


One of my programmer colleagues is telling me that the errors might be because of running python on windows. Is that the case?

**Comment by saeranv** [comment] 2020-11-11 17:18
Is there a reason why you are trying to run the UWG from the repo?  You can
just pip install it and avoid system path errors.

**Comment by saeranv** [comment] 2020-11-12 03:46
@atkamal 

Actually, now that I look at your error, it looks like there might be something wrong in your uwg parameter file. Are you using the initialize_singapore.uwg file? 

I still think it would be good idea to pip install the uwg if you're not planning on modifying the code. So go to your command line and install UWG with:
```
pip install uwg
```
Then the UWG will be available anywhere from python. That's usually a common cause of errors for beginners.

**Comment by atkamal** [comment] 2020-11-12 07:15
Hi Saeran,

I did install it through pip. 

But the errors still persist. I am using the initialize_singapore.uwg and the epw files you recommended above. 

1. Can you let me know which python version and ide you're using? I have tried it in both jupyter notebook and spyder with python 3.8.3. 

2. Also, do you think the initialize files get corrupted during the download?

**Comment by saeranv** [comment] 2020-11-12 21:07
@atkamal 

The version could be the issue, right now we're testing the UWG with versions: 2.7, 3.6, and 3.7 

I don't think the initialize files could have been corrupted, since they're just plain text. Providing the specific path to the file will work fine. The UWG will raise an error at initialization if it can't find the files you've specified, so this can't be the error. 

If it's still giving you an error update your uwg installation by typing `pip install -U uwg` in your command line. I've made a change to the portion of the code giving you issues that will give us a more useful error message. Copy and paste the error message and we can reevaluate. (Just ensure the [PR](https://github.com/ladybug-tools/uwg/pull/142) here is closed, the code hasn't been merged at the the time I'm writing this). 

Finally, you may notice that I modified the README example to import uwg as `from uwg import UWG` rather then the previous `from uwg.uwg import UWG`. You don't have to change this. Either way will work, I just prefer the simpler version.

**Comment by atkamal** [comment] 2020-11-15 07:25
Hi Saeran,

I ran the updated version and got back the following error.

Error while reading parameter at row 5. Got: ['<!doctypehtml>'].
list index out of range

**Comment by saeranv** [comment] 2020-11-15 19:10
@atkamal 

Perfect, now we know what the issue is. Somehow the uwg parameter file you're using has html code which UWG doesn't recognize as a valid input. Check your file, it should be on line number 5. 

Copy and paste the plain text from here: 
https://raw.githubusercontent.com/ladybug-tools/uwg/master/tests/parameters/initialize_singapore.uwg

Or just copy and paste the initialize_singapore.uwg file in the uwg/resources directory. Either should work.

**Comment by atkamal** [comment] 2020-11-16 08:35
Hi @saeranv 

Well I am now getting the following error.

_AssertionError: The sum of reference building fractions defined in bld must equal one. Got: 0.0._

I have checked the text file and the ratio seems to equal to 1. But it's still not working. I have tried it on python 3.6 and 3.7.

**Comment by saeranv** [comment] 2020-11-16 09:47
@atkamal 

My best guess is that your input parameter file is not being copied correctly somehow. 

You can define the UWG model based on default arguments using the from_para_args method:

```
from uwg import UWG

epw = 'SGP_Singapore.486980_IWEC.epw'
par = 'initialize_singapore.uwg'

bld = [('largeoffice', 'pst80', 0.4), ('midriseapartment', 'pst80', 0.6)]
UWG.from_param_args(bldheight=10, blddensity=0.5, vertohor=0.8, 
                    grasscover=0.1, treecover=0.1, zone='1A', bld=bld)

model.generate()
model.simulate()
model.write_epw()
```

The uwg documentation shows all the arguments you can modify: https://www.ladybug.tools/uwg/docs/uwg.uwg.html#uwg.uwg.UWG.from_param_args

**Comment by atkamal** [comment] 2020-11-18 11:06
Hi @saeranv 

I managed to run the uwg using the following code:

**from uwg import UWG

epw = 'C:\\Example\\QAT_DOHA-INTL-AP_411700_IW2.epw'
#par = 'initialize_singapore.uwg'

bld = [('largeoffice', 'pst80', 0.4), ('midriseapartment', 'pst80', 0.6)]
model= UWG.from_param_args(bldheight=10, blddensity=0.5, vertohor=0.8, 
                    grasscover=0.1, treecover=0.1, zone='1A', bld=bld, epw_path=(epw))

model.generate()
model.simulate()
model.write_epw()**


Note, the epw file needed to be changed to another since the one shared by you wasn't working.

PS, I asked another of my colleagues (in Europe) to run the original example, but it isn't working for them either. Do you think there is a problem when you upload the files?

**Comment by saeranv** [comment] 2020-11-19 00:41
@atkamal what was the error given by the Sinapore epw file?

**Comment by saeranv** [comment] 2021-06-23 19:40
Assuming this is resolved, if not new issue can be opened.

**Closed by saeranv** 2021-06-23 19:40 UTC
